"""add visual_records table

Revision ID: be6245ec74a1
Revises: dd856832328b
Create Date: 2026-04-11 18:24:06.609202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6245ec74a1'
down_revision: Union[str, Sequence[str], None] = 'dd856832328b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('emotion', sa.String(), nullable=True),
    sa.Column('stress_level', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_records_id'), 'visual_records', ['id'], unique=False)
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.drop_index(op.f('ix_visual_records_id'), table_name='visual_records')
    op.drop_table('visual_records')
    # ### end Alembic commands ###
